name: Build and test code

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:


jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: go build -mod=readonly ./cmd/helm-autoupdate/main.go
      - name: Verify
        run: go mod verify
      - name: Test
        run: go test -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - name: Docker build
        run: docker build -t helm-autoupdate .